# Generated by Django 4.2.7 on 2023-11-29 16:30

import News_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=500, verbose_name='name game')),
            ],
            options={
                'verbose_name': 'Games',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='title')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='text')),
                ('news_id', models.CharField(blank=True, max_length=500, unique=True, verbose_name='news_id')),
                ('file_news', models.FileField(blank=True, null=True, upload_to=News_app.models.file_news_directory_path, verbose_name='file news')),
                ('news_image_url', models.CharField(blank=True, max_length=500, verbose_name='news image url')),
                ('created', models.DateField(auto_now_add=True, verbose_name='data created')),
                ('original_news', models.CharField(blank=True, max_length=500, verbose_name='original news')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_news', to='News_app.games')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_news_images', models.FileField(blank=True, null=True, upload_to=News_app.models.file_news_directory_path, verbose_name='file news image')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='News_app.news')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(blank=True, max_length=500, unique=True, verbose_name='news_id')),
                ('text_first', models.TextField(blank=True, max_length=500, null=True, verbose_name='first text')),
                ('text_second', models.TextField(blank=True, max_length=500, null=True, verbose_name='second text')),
                ('file_board', models.FileField(blank=True, null=True, upload_to=News_app.models.file_board_directory_path, verbose_name='file board')),
                ('board_image_url', models.CharField(blank=True, max_length=500, verbose_name='board image url')),
                ('created', models.DateField(auto_now_add=True, verbose_name='data created')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_board', to='News_app.games')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'board',
            },
        ),
    ]
